"""create post table

Revision ID: f70f72aec88c
Revises: e0827ddb6811
Create Date: 2023-03-15 14:26:41.062427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70f72aec88c'
down_revision = 'e0827ddb6811'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
